### ISSUE TITLE
Don't say x = (x,y) 

### ISSUE THREAD

**Issue by jidanni** [giswqs/pygis#8]
On https://pygis.io/docs/d_affine.html we see
> x = (x,y)

That is because the author is depending on different fonts to differentiate the two kinds of x.

But that is very bad for [accessibility](https://en.wikipedia.org/wiki/Computer_accessibility) on various devices.

Even using plain ASCII it looks confusing.
Imagine how confusing it is reading it over the phone.

Please use e.g., m=(x,y).

And on https://pygis.io/docs/d_vector_crs_intro.html
> x=x+10

say x'=x+10.

**Comment by giswqs** [comment]
Sorry, the pygis.io website doesn't belong to this repo.
